import { SlashCommandBuilder } from 'discord.js';

export const tradeCommand = new SlashCommandBuilder().setName('trade').setDescription('Find and evaluate Roblox limited item trades')
  .addSubcommand(s => s.setName('link').setDescription('Track a public Roblox inventory (no password or cookie needed)')
    .addStringOption(o => o.setName('user').setDescription('Roblox username or numeric user ID').setRequired(true)))
  .addSubcommand(s => s.setName('inventory').setDescription('Show your available items and their Rolimons value/RAP'))
  .addSubcommand(s => s.setName('find').setDescription('Find verified ad matches and generate counteroffers')
    .addStringOption(o => o.setName('mode').setDescription('Override your saved mode for this search').addChoices(
      { name: 'Any', value: 'any' }, { name: 'Upgrade: give more items than you receive', value: 'upgrade' }, { name: 'Downgrade: receive more items than you give', value: 'downgrade' }))
    .addStringOption(o => o.setName('target').setDescription('Wanted item ID, name or acronym; overrides watch list').setAutocomplete(true))
    .addIntegerOption(o => o.setName('results').setDescription('Number of recommendations to display').setMinValue(1).setMaxValue(3)))
  .addSubcommand(s => s.setName('analyze').setDescription('Check a specific item exchange against both inventories')
    .addStringOption(o => o.setName('partner').setDescription('Other Roblox username or ID').setRequired(true))
    .addStringOption(o => o.setName('give').setDescription('1–4 catalog item IDs separated by commas; repeat an ID for multiple copies').setRequired(true))
    .addStringOption(o => o.setName('receive').setDescription('1–4 catalog item IDs separated by commas').setRequired(true)))
  .addSubcommand(s => s.setName('settings').setDescription('View or update trade filters; percentages are relative to your given totals')
    .addStringOption(o => o.setName('mode').setDescription('Default search mode').addChoices({ name: 'Any', value: 'any' }, { name: 'Upgrade', value: 'upgrade' }, { name: 'Downgrade', value: 'downgrade' }))
    .addNumberOption(o => o.setName('min_value_gain').setDescription('Minimum value gain %; allow a negative value to permit losses').setMinValue(-50).setMaxValue(1000))
    .addNumberOption(o => o.setName('min_rap_gain').setDescription('Minimum RAP gain %').setMinValue(-100).setMaxValue(1000))
    .addNumberOption(o => o.setName('max_overpay').setDescription('Max (given value − received value) / received value %').setMinValue(0).setMaxValue(50))
    .addNumberOption(o => o.setName('max_partner_loss').setDescription('Max (received value − given value) / received value %').setMinValue(0).setMaxValue(50))
    .addIntegerOption(o => o.setName('min_demand').setDescription('-1 permits unknown; 0 terrible, 1 low, 2 normal, 3 high, 4 amazing').setMinValue(-1).setMaxValue(4))
    .addNumberOption(o => o.setName('max_rap_value_ratio').setDescription('Maximum incoming RAP / assigned value ratio').setMinValue(1).setMaxValue(10))
    .addBooleanOption(o => o.setName('exclude_projected').setDescription('Reject incoming items marked projected'))
    .addIntegerOption(o => o.setName('max_ad_age').setDescription('Maximum ad age in minutes').setMinValue(1).setMaxValue(1440)))
  .addSubcommand(s => s.setName('watch').setDescription('Add a wanted item to searches and alerts')
    .addStringOption(o => o.setName('item').setDescription('Item ID, name or acronym').setAutocomplete(true).setRequired(true)))
  .addSubcommand(s => s.setName('unwatch').setDescription('Remove a wanted item; use all to clear the list')
    .addStringOption(o => o.setName('item').setDescription('Item ID, name, acronym, or all').setRequired(true)))
  .addSubcommand(s => s.setName('lock').setDescription('Never offer any copies of this item')
    .addStringOption(o => o.setName('item').setDescription('Item ID, name or acronym').setAutocomplete(true).setRequired(true)))
  .addSubcommand(s => s.setName('unlock').setDescription('Allow an item to be offered again; use all to clear locks')
    .addStringOption(o => o.setName('item').setDescription('Item ID, name, acronym, or all').setRequired(true)))
  .addSubcommand(s => s.setName('alerts').setDescription('Enable or disable personal trade recommendation DMs')
    .addBooleanOption(o => o.setName('enabled').setDescription('Enable DMs for matching trades under your saved settings').setRequired(true)))
  .addSubcommand(s => s.setName('status').setDescription('Show tracked account, alert status and preferences'))
  .addSubcommand(s => s.setName('forget').setDescription('Delete your tracked account, settings and alert history'))
  .addSubcommand(s => s.setName('help').setDescription('Explain commands and trade calculations'));

export const commandJSON = [tradeCommand.toJSON()];
